import re
from collections import defaultdict
import glob
import os

def extract_max_groups(filenames):
    # Dictionary to store max group number for each year pair
    max_groups = defaultdict(int)
    
    # Regex pattern to extract years and group numbers
    pattern = r'start\.(\d+)\.end\.(\d+)\.group\.(\d+)\.csv'
    
    for filename in filenames:
        match = re.search(pattern, filename)
        if match:
            start_year = int(match.group(1))
            end_year = int(match.group(2))
            group_num = int(match.group(3))
            
            year_pair = (start_year, end_year)
            max_groups[year_pair] = max(max_groups[year_pair], group_num)
    
    return max_groups

def write_matlab_script_params(max_groups, output_file):
    """
    Write the year pairs and max groups to a file in the format needed for run_matlab_optimization.sh
    
    Args:
        max_groups (dict): Dictionary mapping (start_year, end_year) tuples to max group numbers
        output_file (str): Path to the output file
    """
    # Sort the year pairs to ensure consistent output
    sorted_pairs = sorted(max_groups.items())
    
    # Prepare the arrays
    start_years = []
    end_years = []
    max_groups_list = []
    
    for (start, end), max_group in sorted_pairs:
        start_years.append(str(start))
        end_years.append(str(end))
        max_groups_list.append(str(max_group))
    
    # Write to file
    with open(output_file, 'w') as f:
        f.write("# Generated by generator_params.py\n\n")
        # Format the arrays with proper quoting and parentheses
        start_years_str = " ".join(f"'{year}'" for year in start_years)
        end_years_str = " ".join(f"'{year}'" for year in end_years)
        max_groups_str = " ".join(max_groups_list)
        
        f.write(f"START_YEARS=({start_years_str})\n")
        f.write(f"END_YEARS=({end_years_str})\n")
        f.write(f"MAX_GROUPS=({max_groups_str})\n")

if __name__ == "__main__":
    # Get the directory of the current script
    # tmp data folder
    tmp_dir = "/n/hausmann_lab/lab/atlas/bustos_yildirim/weights_generator/generator/data/temp"
    
    # Define the path to the matrices directory
    matrices_dir = "/n/hausmann_lab/lab/atlas/bustos_yildirim/weights_generator/generator/data/matrices"
    files = glob.glob(os.path.join(matrices_dir, "*.csv"))
    
    # Extract max groups
    result = extract_max_groups(files)

    # Print results to console
    print("Year pairs and max groups found:")
    for (start, end), max_group in sorted(result.items()):
        print(f"Start year: {start}, End year: {end}, Max group: {max_group}")
    
    # Write to file in MATLAB script format
    output_file = os.path.join(tmp_dir, "matlab_script_params.txt")
    write_matlab_script_params(result, output_file)
    print(f"\nParameters written to: {output_file}")