SOURCE_TARGET_ENABLED_PAIRS = [
    # Backward HS conversions
    {
        "direction": "backward",
        "source_class": "HS1996",
        "target_class": "HS1992",
        "source_year": "1996",
        "target_year": "1995",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "HS2002",
        "target_class": "HS1996",
        "source_year": "2002",
        "target_year": "2001",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "HS2007",
        "target_class": "HS2002",
        "source_year": "2007",
        "target_year": "2006",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "HS2012",
        "target_class": "HS2007",
        "source_year": "2012",
        "target_year": "2011",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "HS2017",
        "target_class": "HS2012",
        "source_year": "2017",
        "target_year": "2016",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "HS2022",
        "target_class": "HS2017",
        "source_year": "2022",
        "target_year": "2021",
        "enabled": False,
    },
    # SITC conversions
    {
        "direction": "backward",
        "source_class": "HS1992",
        "target_class": "SITC3",
        "source_year": "1992",
        "target_year": "1988",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "SITC3",
        "target_class": "SITC2",
        "source_year": "1988",
        "target_year": "1987",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "SITC2",
        "target_class": "SITC1",
        "source_year": "1987",
        "target_year": "1976",
        "enabled": False,
    },
    # Forward HS conversions
    {
        "direction": "forward",
        "source_class": "HS1992",
        "target_class": "HS1996",
        "source_year": "1995",
        "target_year": "1996",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "HS1996",
        "target_class": "HS2002",
        "source_year": "2001",
        "target_year": "2002",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "HS2002",
        "target_class": "HS2007",
        "source_year": "2006",
        "target_year": "2007",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "HS2007",
        "target_class": "HS2012",
        "source_year": "2011",
        "target_year": "2012",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "HS2012",
        "target_class": "HS2017",
        "source_year": "2016",
        "target_year": "2017",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "HS2017",
        "target_class": "HS2022",
        "source_year": "2021",
        "target_year": "2022",
        "enabled": False,
    },
    # Forward SITC conversions
    {
        "direction": "forward",
        "source_class": "SITC3",
        "target_class": "HS1992",
        "source_year": "1988",
        "target_year": "1992",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "SITC2",
        "target_class": "SITC3",
        "source_year": "1987",
        "target_year": "1988",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "SITC1",
        "target_class": "SITC2",
        "source_year": "1975",
        "target_year": "1976",
        "enabled": False,
    },
    # FORWARD NAICS
    {
        "direction": "forward",
        "source_class": "NAICS1997",
        "target_class": "NAICS2002",
        "source_year": "1997",
        "target_year": "2002",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "NAICS2002",
        "target_class": "NAICS2007",
        "source_year": "2002",
        "target_year": "2007",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "NAICS2007",
        "target_class": "NAICS2012",
        "source_year": "2007",
        "target_year": "2012",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "NAICS2012",
        "target_class": "NAICS2017",
        "source_year": "2012",
        "target_year": "2017",
        "enabled": False,
    },
    {
        "direction": "forward",
        "source_class": "NAICS2017",
        "target_class": "NAICS2022",
        "source_year": "2017",
        "target_year": "2022",
        "enabled": False,
    },
    # BACKWARD NAICS
    {
        "direction": "backward",
        "source_class": "NAICS2022",
        "target_class": "NAICS2017",
        "source_year": "2022",
        "target_year": "2017",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "NAICS2017",
        "target_class": "NAICS2012",
        "source_year": "2017",
        "target_year": "2012",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "NAICS2012",
        "target_class": "NAICS2007",
        "source_year": "2012",
        "target_year": "2007",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "NAICS2012",
        "target_class": "NAICS2007",
        "source_year": "2012",
        "target_year": "2007",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "NAICS2007",
        "target_class": "NAICS2002",
        "source_year": "2007",
        "target_year": "2002",
        "enabled": False,
    },
    {
        "direction": "backward",
        "source_class": "NAICS2002",
        "target_class": "NAICS1997",
        "source_year": "2002",
        "target_year": "1997",
        "enabled": False,
    },
]
